// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnjRbtLLSUpB2PVyCLiRKvsmAfi-4LPc',
    appId: '1:320882070130:web:8244a0c0e4bed3da8ee8eb',
    messagingSenderId: '320882070130',
    projectId: 'carwash-b9a26',
    authDomain: 'carwash-b9a26.firebaseapp.com',
    databaseURL: 'https://carwash-b9a26-default-rtdb.firebaseio.com',
    storageBucket: 'carwash-b9a26.appspot.com',
    measurementId: 'G-3DPV39YFWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUkiO-EFbjDQNnyyloVl5FcM3iUMaGOt8',
    appId: '1:320882070130:android:bf9f73b2b77b59df8ee8eb',
    messagingSenderId: '320882070130',
    projectId: 'carwash-b9a26',
    databaseURL: 'https://carwash-b9a26-default-rtdb.firebaseio.com',
    storageBucket: 'carwash-b9a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SJeUBPiE6RJ-5HwzSSEaxEVYSi-1o-A',
    appId: '1:320882070130:ios:a6ab175b28d70b508ee8eb',
    messagingSenderId: '320882070130',
    projectId: 'carwash-b9a26',
    databaseURL: 'https://carwash-b9a26-default-rtdb.firebaseio.com',
    storageBucket: 'carwash-b9a26.appspot.com',
    androidClientId:
        '320882070130-4vist1khs9vjjp04h3mk6mp86n53f2a9.apps.googleusercontent.com',
    iosClientId:
        '320882070130-vcup6udpflnidu8jk2jtsuqi68v5kfm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.carWashDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8SJeUBPiE6RJ-5HwzSSEaxEVYSi-1o-A',
    appId: '1:320882070130:ios:a6ab175b28d70b508ee8eb',
    messagingSenderId: '320882070130',
    projectId: 'carwash-b9a26',
    databaseURL: 'https://carwash-b9a26-default-rtdb.firebaseio.com',
    storageBucket: 'carwash-b9a26.appspot.com',
    androidClientId:
        '320882070130-4vist1khs9vjjp04h3mk6mp86n53f2a9.apps.googleusercontent.com',
    iosClientId:
        '320882070130-vcup6udpflnidu8jk2jtsuqi68v5kfm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.carWashDashboard',
  );
}
